import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import json from "@eslint/json";
import { defineConfig } from "eslint/config";
import stylistic from "@stylistic/eslint-plugin";

export default defineConfig([
    {
        ignores: ["**/dist/**/*"],
    },
    {
        files: ["**/*.{js,mjs,cjs,ts,mts,cts}"],
        plugins: {
            js,
            "@stylistic": stylistic,
        },
        rules: {
            "@stylistic/indent": ["error", 4],
            "@stylistic/semi": ["error", "always"],
            "@stylistic/no-extra-semi": "error",
            "@stylistic/line-comment-position": ["error", { position: "above" }],
            "@stylistic/no-mixed-operators": "error",
            "@stylistic/brace-style": ["error", "1tbs"],

            "@stylistic/quotes": ["warn", "double"],
            "@stylistic/array-bracket-spacing": ["warn", "never", { singleValue: false }],
            "@stylistic/semi-style": ["warn", "last"],
        },
        extends: [
            "js/recommended",
            tseslint.configs.recommendedTypeChecked,
            tseslint.configs.stylisticTypeChecked,
            stylistic.configs.recommended,

        ],
        languageOptions: {
            globals: globals.node,
            parserOptions: {
                projectService: true,
            },
        },
    },

    {
        files: ["**/*.json"],
        plugins: { json },
        language: "json/json5",
        extends: ["json/recommended"],
        // As this is autogenerated with 'an error' in it, Im just going to disable that stuff :3
        ignores: ["./package-lock.json"],
    },
]);
