import type { ICommand } from "../interfaces/ICommand.js";
import { selectRandom } from "../utils/utils.js";

const woofMessages = [
    "awoooo ruff ruff :3.",
    "erm... no resets... WOOF WOOF",
    "brown split incoming :3c",
    "awooooo streamer washed",
    "ruff ruff go faster!!!",
    "puppy believes in the run :3",
    "awooo that was kinda clean",
    "woof woof DONT CHOKE",
    "puppy says keep going!!!",
    "erm... that was NOT optimal...",
    "awooooo +0.3 is basically green",
    "ruff ruff SAVE THE RUN",
    "awooo the portals are cooperating",
    "woof... angle decay...",
    "puppy says this is THE ONE",
    "awooooo gamer mode activated",
    "ruff ruff movement diff",
    "puppy saw that portal placement...",
    "erm... who needs a good split anyway",
    "woof woof WOAH",
    "puppy says dont look at the timer",
    "ruff ruff absolutely gaming",
    "puppy has faith... somehow",
    "awooooo that chamber was FREE",
    "woof woof go go go!!!",
    "erm... slightly washed... but recoverable",
    "puppy says LOCK IN",
    "ruff ruff clean movement!!!",
    "puppy smells a sub-1:16...",
    "awooooo the dog believes",
    "woof woof no silly mistakes",
    "erm... that was a little silly",
    "puppy says we ball :3",
    "ruff ruff faster faster faster",
    "puppy is watching the splits...",
    "awooooo",
    "woof... tragic...",
    "puppy says never back down",
    "ruff ruff portal go brrrr",
    "puppy says ur so speedruns",
    "awoo... streamer has forgotten how to portal",
    "woof woof THAT WAS CLOSE",
    "puppy says keep the run alive :3",
    "awooooo PB INCOMING",
    "ruff ruff no pressure :3c",
    "erm... the dog saw that...",
    "puppy says trust the strat",
    "awooo clean clean clean",
    "woof woof GAMER ALERT",
    "puppy detected silly movement",
    "awooooo STOP LOSING TIME",
    "ruff ruff +10 pace WOOF",
    "puppy says the split is lying",
    "erm... mathematically recoverable",
    "awooo the run is alive!!!",
    "woof woof occuboinkal or something idk im larping",
    "puppy believes in 1:16 pace :3",
    "awooooo portal 2 go brrrrr",
    "ruff ruff skill issue detected",
    "puppy says we're so back",
    "erm... we're so cooked...",
    "awooo HUGE DOG GAMING",
    "woof woof PB OR DEATH",
    "puppy says one more run :3",
    "martin8 jumpscare",
];

const woof: ICommand = {
    function: (reply: (text: string) => void) => {
        reply(selectRandom(woofMessages));
    },
    name: "woof",
    parameters: { aliases: ["puppy", "dog"] },
    description: "*awoo's at you*"
};


export { woof };